name: Test Package

on:
  push:
    branches: 
      - master
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@quanhuynhnt'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: 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
